DIRECTORY:
  dataset: ./data #개발 경로에 맞게 수정하세요 !
  
TRAINER :
  is_colab: False
  is_trained: False
  train_serial: '20220616_190000'
  model: deeplabv3p
  optimizer: adamw
  learning_rate: 5.0e-4
  n_epochs: 150
  early_stopping_target: val_mIoU
  early_stopping_patience: 10
  early_stopping_mode: max #min
  gpu: 0
  seed: 42
  apply_aug: classmix
  weak_threshold: 0.7
  strong_threshold: 0.97
  apply_reco: True
  temp: 0.5
  num_queries: 256
  num_negatives: 512
  
MODEL:
  num_labels: 5
  output_dim: 256

DATALOADER:
  batch_size: 5

LOGGER:
  wandb: True
  logging_interval: 100
  plot:
    - loss
    - mIoU
    - elapsed_time