DIRECTORY:
  dataset: C:/Users/Admin/OneDrive/C Documents/GitHub/aivill_seg/dataset #개발 경로에 맞게 수정하세요 !
  
TRAINER :
  model: deeplabv3p
  optimizer: nadam
  learning_rate: 5.0e-4
  n_epochs: 200
  early_stopping_target: val_mIoU
  early_stopping_patience: 20
  early_stopping_mode: max #min
  gpu: 0,1
  seed: 42
  apply_aug: classmix
  weak_threshold: 0.7
  strong_threshold: 0.97
  apply_reco: True
  temp: 0.5
  num_queries: 256
  num_negatives: 512
  save_period: 1
  log_per_iter: 20
  val: true
  val_per_epochs: 10
  gamma: 0.5
  sharp_temp: 0.5
  save_dir: saved/
  log_dir: saved/
  
MODEL:
  num_labels: 5
  output_dim: 256
  psmt:
    supervised: false
    semi: true
    resnet: 101
    sup_loss: OHEM
    un_loss: semi_ce
    warm_up_epoch: 0

DATALOADER:
  batch_size: 5

LOGGER:
  wandb: True
  logging_interval: 100
  plot:
    - loss
    - mIoU
    - elapsed_time

n_labeled_examples: 372
ramp_up: 12
unsupervised_w: 3.0
ignore_index: 255
lr_scheduler: Poly
use_weak_labels: false
weakly_loss_w: 0.4
name: "Co-Seg_aicomp"
experim_name: final_test

train_supervised:
  crop_size: 512
  batch_size: 8
  shuffle: true
  scale: true


optimizer:
  type: SGD
  args:
    lr: 4.5e-3
    weight_decay: 1e-4
    momentum: 0.9

